#!./lua

local ui = require("ui")

local shell = require("user.shell")
local debugger = require("user.debugger")

ui.init()
shell.init(ui)
debugger.init(ui)

local columns = ui.in_root(ui.hbox({ spacing = 4, scroll_by = 20 }))
local history
local add_column

local function eval(self, text)
   if text:match("^$ ") then
      return shell.eval(self, text:sub(2))
   elseif text:match("^debug") then
      return debugger.new(self)
   else
      self.text = self.parent.parent.name .. #self.parent.parent.children .. " = " .. self.text
      self:resize()
      self.parent.parent.data.add_prompt("")
   end
end

local function on_key(self, key)
   if self.text:match("^$ ") then
      return shell.on_key(self, key)
   end
end

local function add_prompt(text, dir)
   local prompt = ui.text(text, {
      cursor = #text,
      editable = true,
      eval = eval,
      on_key = on_key,
   })
   local window = ui.vbox({ name = "window", scrollable = false, min_w = 492, spacing = 4, fill = 0x333333, border = 0x00ffff }, {
      prompt
   })
   ui.set_focus(prompt)
   if dir == "right" then
      history = add_column()
   end
   history:add_child(window)
end

add_column = function()
   return columns:add_child(ui.vbox({
      name = string.char(64 + #columns.children + 1),
      scrollable = false,
      spacing = 4,
      data = {
         add_prompt = add_prompt,
      }
   }))
end

history = add_column()
history.data.add_prompt("")

local fullscreen = false

ui.on_key(function(key, is_text, is_repeat)
   --print(key)
   if key == "Escape" then
      ui.quit()
   elseif key == "Tab" then
      add_prompt("", "right")
   elseif key == "Ctrl F" and not is_repeat then
      fullscreen = not fullscreen
      ui.fullscreen(fullscreen)
   end
end)

ui.on_mouse_drag(function(x, y)
end)

ui.run(function()
   shell.frame()
end)
